package com.readstorm.app.domain.models

data class AppSettings(
    var downloadPath: String = "downloads",
    var maxConcurrency: Int = 10,
    var aggregateSearchMaxConcurrency: Int = 10,
    var minIntervalMs: Int = 300,
    var maxIntervalMs: Int = 800,
    var exportFormat: String = "txt",
    var proxyEnabled: Boolean = false,
    var proxyHost: String = "",
    var proxyPort: Int = 0,
    var readerFontSize: Int = 20,
    var readerFontName: String = "",
    var readerLineHeight: Int = 36,
    var readerParagraphSpacing: Int = 0,
    var readerBackground: String = "#FFFBF0",
    var readerForeground: String = "#1E293B",
    var readerDarkMode: Boolean = false,
    var readerExtendIntoCutout: Boolean = false,
    var readerContentMaxWidth: Int = 0,
    var readerTopReservePx: Int = 4,
    var readerBottomReservePx: Int = 0,
    var readerBottomStatusBarReservePx: Int = 0,
    var readerHorizontalInnerReservePx: Int = 0,
    var readerSidePaddingPx: Int = 12,
    var readerUseVolumeKeyPaging: Boolean = false,
    var readerUseSwipePaging: Boolean = false,
    var readerHideSystemStatusBar: Boolean = false,
    var bookshelfProgressLeftPaddingPx: Int = 5,
    var bookshelfProgressRightPaddingPx: Int = 5,
    var bookshelfProgressTotalWidthPx: Int = 106,
    var bookshelfProgressMinWidthPx: Int = 72,
    var bookshelfProgressBarToPercentGapPx: Int = 8,
    var bookshelfProgressPercentTailGapPx: Int = 24,
    var enableDiagnosticLog: Boolean = false,
    var autoResumeAndRefreshOnStartup: Boolean = false,
    var readerAutoPrefetchEnabled: Boolean = true,
    var readerPrefetchBatchSize: Int = 10,
    var readerPrefetchLowWatermark: Int = 3
)
