@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@if "%DEBUG%"=="" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows generated by Gradle.
@rem
@rem ##########################################################################

setlocal

set APP_HOME=%~dp0
@rem Normalize APP_HOME to remove trailing backslash
if "%APP_HOME:~-1%"=="\\" set APP_HOME=%APP_HOME:~0,-1%

set WRAPPER_JAR=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
if not exist "%WRAPPER_JAR%" (
  echo ERROR: Could not find Gradle Wrapper jar at "%WRAPPER_JAR%" 1>&2
  echo This project is missing gradle\wrapper\gradle-wrapper.jar. 1>&2
  exit /b 1
)

if not "%JAVA_HOME%"=="" (
  set "JAVACMD=%JAVA_HOME%\bin\java.exe"
) else (
  set "JAVACMD=java"
)

"%JAVACMD%" -Dorg.gradle.appname=%~n0 -classpath "%WRAPPER_JAR%" org.gradle.wrapper.GradleWrapperMain %*
set EXIT_CODE=%ERRORLEVEL%

endlocal & exit /b %EXIT_CODE%
